package pojo;
// Generated Oct 8, 2019 3:50:30 PM by Hibernate Tools 4.3.1



/**
 * ImageTable generated by hbm2java
 */
public class ImageTable  implements java.io.Serializable {


     private Integer id;
     private byte[] image;

    public ImageTable() {
    }

    public ImageTable(byte[] image) {
       this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


