package pojo;
// Generated Oct 8, 2019 3:50:30 PM by Hibernate Tools 4.3.1

import dao.luar;
import dao.trans;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblLuar generated by hbm2java
 */
@ManagedBean
public class TblLuar  implements java.io.Serializable {


     private Integer id;
     private String postId;
     private int keluar;
     private String info;

    public TblLuar() {
    }

    public TblLuar(String postId, int keluar) {
       this.postId = postId;
       this.keluar = keluar;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }
    public int getKeluar() {
        return this.keluar;
    }
    
    public void setKeluar(int keluar) {
        this.keluar = keluar;
    }

public void save() {
 luar plg = new luar();
 plg.addluar(this);
        setInfo("Sukses");
 } 

    /**
     * @return the info
     */
    public String getInfo() {
        return info;
    }

    /**
     * @param info the info to set
     */
    public void setInfo(String info) {
        this.info = info;
    }
public List<TblLuar> getallrecords() {
 luar plg = new luar();
 List<TblLuar> lPlg = plg.retrieveTblLuar();
 return lPlg;
 }
}


