package pojo;
// Generated Oct 8, 2019 3:50:30 PM by Hibernate Tools 4.3.1

import dao.trans;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblTransaction generated by hbm2java
 */
@ManagedBean
public class TblTransaction  implements java.io.Serializable {


     private Integer id;
     private String postId;
     private String name;
     private String email;
     private int amount;

    public TblTransaction() {
    }

    public TblTransaction(String postId, String name, String email, int amount) {
       this.postId = postId;
       this.name = name;
       this.email = email;
       this.amount = amount;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
public List<TblTransaction> getallrecords() {
 trans plg = new trans();
 List<TblTransaction> lPlg = plg.retrieveTblTransaction();
 return lPlg;
 }



}


