package pojo;
// Generated Oct 8, 2019 3:34:25 PM by Hibernate Tools 4.3.1



/**
 * TblLuar generated by hbm2java
 */
public class TblLuar  implements java.io.Serializable {


     private Integer id;
     private String postId;
     private int keluar;

    public TblLuar() {
    }

    public TblLuar(String postId, int keluar) {
       this.postId = postId;
       this.keluar = keluar;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }
    public int getKeluar() {
        return this.keluar;
    }
    
    public void setKeluar(int keluar) {
        this.keluar = keluar;
    }




}


