package pojo;
// Generated Oct 8, 2019 3:34:25 PM by Hibernate Tools 4.3.1

import dao.post;
import dao.trans;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblTransaction generated by hbm2java
 */
@ManagedBean
public class TblTransaction  implements java.io.Serializable {


     private Integer id;
     private String postId;
     private String name;
     private String email;
     private int amount;
private String info;
    public TblTransaction() {
    }

    public TblTransaction(Integer id,String postId, String name, String email, int amount) {
        this.id=id;
       this.postId = postId;
       this.name = name;
       this.email = email;
       this.amount = amount;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }


public void save() {
 trans plg = new trans();
 plg.addtrans(this);
        setInfo("Sukses Menambah Data");
 } 

public void save(String id) {
 trans plg = new trans();
 postId = id;
 plg.addtrans(this);
        setInfo("Sukses Menambah Data");
 } 
 
    /**
     * @return the info
     */
    public String getInfo() {
        return info;
    }

    /**
     * @param info the info to set
     */
    public void setInfo(String info) {
        this.info = info;
    }

}


